/*

    DIY Layout Creator (DIYLC).
    Copyright (c) 2009-2025 held jointly by the individual authors.

    This file is part of DIYLC.

    DIYLC is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    DIYLC is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with DIYLC.  If not, see <http://www.gnu.org/licenses/>.

*/
package org.diylc.editor.compressor;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.diylc.components.connectivity.CopperTrace;
import org.diylc.components.connectivity.CurvedTrace;
import org.diylc.components.connectivity.CutLine;
import org.diylc.components.connectivity.Dot;
import org.diylc.components.connectivity.GroundFill;
import org.diylc.components.connectivity.Line;
import org.diylc.components.connectivity.MultimeterProbe;
import org.diylc.components.connectivity.SolderPad;
import org.diylc.components.connectivity.TraceCut;
import org.diylc.core.IBoard;
import org.diylc.core.IContinuity;
import org.diylc.core.IDIYComponent;
import org.diylc.core.ISwitch;
import org.diylc.core.Project;

/**
 * Splits project components into the categories relevant for layout compression: real parts that
 * get placed on the board, connectivity-only components that merely carry connections and get
 * replaced by generated wiring, boards that get replaced by the generated board, and decorations
 * that play no electrical role.
 *
 * @author Layout Compressor contributors
 */
public class ComponentClassifier {

  // components that only carry or modify connections and can be regenerated by routing;
  // physical hardware from the same palette category (terminal blocks, turrets, eyelets,
  // solder lugs) must be placed like any other part and deliberately isn't listed
  private static final Set<Class<?>> REGENERABLE_CLASSES = new HashSet<Class<?>>(
      Arrays.asList(CopperTrace.class, CurvedTrace.class, GroundFill.class, SolderPad.class,
          Dot.class, Line.class, TraceCut.class, CutLine.class, MultimeterProbe.class));

  public Classification classify(Project project) {
    Classification result = new Classification();
    for (IDIYComponent<?> c : project.getComponents()) {
      if (c instanceof IBoard) {
        result.boards.add(c);
      } else if (isConnectivityOnly(c)) {
        result.connectivity.add(c);
      } else if (hasNoStickyPoints(c)) {
        result.decorations.add(c);
      } else {
        result.realParts.add(c);
      }
    }
    return result;
  }

  private boolean isConnectivityOnly(IDIYComponent<?> c) {
    if (c instanceof ISwitch) {
      return false;
    }
    if (c instanceof IContinuity) {
      return true;
    }
    return REGENERABLE_CLASSES.contains(c.getClass());
  }

  private boolean hasNoStickyPoints(IDIYComponent<?> c) {
    for (int i = 0; i < c.getControlPointCount(); i++) {
      if (c.isControlPointSticky(i)) {
        return false;
      }
    }
    return true;
  }

  public static class Classification {

    private final List<IDIYComponent<?>> realParts = new ArrayList<IDIYComponent<?>>();
    private final List<IDIYComponent<?>> connectivity = new ArrayList<IDIYComponent<?>>();
    private final List<IDIYComponent<?>> boards = new ArrayList<IDIYComponent<?>>();
    private final List<IDIYComponent<?>> decorations = new ArrayList<IDIYComponent<?>>();

    public List<IDIYComponent<?>> getRealParts() {
      return realParts;
    }

    public List<IDIYComponent<?>> getConnectivity() {
      return connectivity;
    }

    public List<IDIYComponent<?>> getBoards() {
      return boards;
    }

    public List<IDIYComponent<?>> getDecorations() {
      return decorations;
    }
  }
}
